### ISSUE TITLE
blitz3d config error

### ISSUE THREAD

**Issue by jubalh** [blitz3d-ng/blitz3d-ng#11]
Getting the following error:

```
bin/blitz3d config && premake4
Traceback (most recent call last):
	2: from bin/blitz3d:5:in `<main>'
	1: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
```

**Comment by kfprimm** [comment]
As mentioned in #12, the conversion to cmake has been completed & documented.

**Comment by kfprimm** [comment]
Also @jubalh, I see you're on linux. Jump into the discord (https://discord.gg/E6kTHXn) if you need any help. macOS/linux are still very experimental.
