### ISSUE TITLE
Can't build Blitz3D-NG

### ISSUE THREAD

**Issue by Yackerw** [blitz3d-ng/blitz3d-ng#12]
"Error: module './build/src/init' not found:
no field package.preload['./build/src/init']"
followed by complaining about missing a lot of lua files. Am I missing something here or...?

**Comment by jubalh** [comment]
I got https://github.com/blitz3d-ng/blitz3d-ng/issues/11
You dont get that?

Project seems pretty inactive to me.

**Comment by Yackerw** [comment]
Your issue is you haven't installed the dependencies. You need to do gem install bundler in the command prompt, then bundler install when in the directory of the repo. You also need a version of Ruby between 2.0 and 2.4 iirc (i used 2.3, I distinctly recall 2.5 not working) and the Ruby developer kit installed.

My issue lies in after all that is done, the Ruby program seems to just give up because of missing files. The build bot linked in the readme.md in the github also seems to have the same issue, so i have no idea as to how the creator would've not noticed this if something was actually wrong with how he set up the github or something.

**Comment by kfprimm** [comment]
Merry Christmas/Happy New Year!

I've finished the cmake conversion on Windows & updated the README accordingly. You can also download a prebuilt version from Appveyor.

https://github.com/blitz3d-ng/blitz3d-ng#download

**Comment by jubalh** [comment]
Thanks @kfprimm.
However I think some infos are missing.

I'm not a ruby person. And I don't see this documented in the readme:

```
bin/blitz3d config
Traceback (most recent call last):
	2: from bin/blitz3d:5:in `<main>'
	1: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)

gem install bundle

bin/blitz3d config      
Traceback (most recent call last):
	8: from bin/blitz3d:6:in `<main>'
	7: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	6: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:109:in `setup'
	5: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
	4: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
	3: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
	2: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
	1: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
/usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find i18n-0.8.1 in any of the sources (Bundler::GemNotFound)

sudo gem install i18n                                                                                                                                      :(
Fetching: concurrent-ruby-1.1.4.gem (100%)
Successfully installed concurrent-ruby-1.1.4
Fetching: i18n-1.3.0.gem (100%)

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

Successfully installed i18n-1.3.0
Parsing documentation for concurrent-ruby-1.1.4
Installing ri documentation for concurrent-ruby-1.1.4
Parsing documentation for i18n-1.3.0
Installing ri documentation for i18n-1.3.0
Done installing documentation for concurrent-ruby, i18n after 5 seconds
2 gems installed

 bin/blitz3d config   
Traceback (most recent call last):
	8: from bin/blitz3d:6:in `<main>'
	7: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	6: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:109:in `setup'
	5: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
	4: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
	3: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
	2: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
	1: from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
/usr/lib64/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find i18n-0.8.1 in any of the sources (Bundler::GemNotFound)
```

It seems you should mention how to install all those deps in one line in the readme.
Because the readme claims:

```
$ git clone --recursive https://github.com/blitz3d-ng/blitz3d-ng
$ cd blitz3d-ng
$ apt-get install -y build-essential libwxgtk3.0-dev
$ bin/blitz3d config && make ENV=release
```

is all one needs.

**Comment by kfprimm** [comment]
You have to run `bundle` to install the dependencies. Just running `gem install i18n` doesn't guarantee the correct version.

Feel free to submit a PR with the updated docs.
