### ISSUE TITLE
Ruby errors out when building [Ubuntu 21.04, Linux]

### ISSUE THREAD

**Issue by SquaredWave** [blitz3d-ng/blitz3d-ng#26]
Error after executing `bin/blitz3d config && make ENV=release`
```
Traceback (most recent call last):
        8: from bin/blitz3d:6:in `<main>'
        7: from /usr/lib/ruby/2.7.0/bundler.rb:174:in `require'
        6: from /usr/lib/ruby/2.7.0/bundler.rb:151:in `setup'
        5: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
        4: from /usr/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
        3: from /usr/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
        2: from /usr/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
        1: from /usr/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
/usr/lib/ruby/2.7.0/bundler/spec_set.rb:86:in `block in materialize': Could not find concurrent-ruby-1.1.6 in any of the sources (Bundler::GemNotFound)
```

**Comment by kfprimm** [comment]
You probably need to run `bundle` to install the dependencies.

Regardless, `bin/blitz3d config` has been removed and ruby is no longer required to build.
